### ISSUE TITLE
1.16.5 availability

### ISSUE THREAD

**Issue by jakey1995abc** [Trikzon/Sneak-Through-Berries#10]
Is this mod still compatible with 1.16.5? If so could you add the tag for it so that CurseForge client users can find and add the mod to their packs?

**Comment by ex0planetary** [comment]
Should be compatible with 1.16.5 (since that update barely changed MC's codebase at all). It would be really nice to get it tagged for that version though - really difficult to put it in modpacks rn.

**Comment by Trikzon** [comment]
Finally ported this mod to 1.16.5 (and all the way up to and including 1.19) the other day.
