### ISSUE TITLE
crashed 1.16.5 forge version 36.1.25

### ISSUE THREAD

**Issue by DjBigNic977878** [Trikzon/Sneak-Through-Berries#12]
sneak through berries crashed for no apparent reson
[crash-2021-06-17_21.09.02-fml.txt](https://github.com/Trikzon/sneak-through-berries/files/6674526/crash-2021-06-17_21.09.02-fml.txt)

**Comment by Trikzon** [comment]
This crash had something to do with the config, which doesn't exist anymore in newer versions.
