### ISSUE TITLE
1.17?

### ISSUE THREAD

**Issue by NebelNidas** [Trikzon/Sneak-Through-Berries#13]
I'm not usually the guy annoying devs with these sort of questions, but since this mod seems quite abandoned, I wanted to ask if you plan on updating it to the latest MC version.

**Comment by Trikzon** [comment]
I will definitely get around to it. The problem is that each mod I update takes *at least* a few hours to update (read a whole night). My focus isn't on this right now, but I have been updating about one mod a week. You've just got to wait

**Comment by Trikzon** [comment]
Updated to 1.17.1 (and all new versions up to and including 1.19)
