### ISSUE TITLE
Version 1.16.1-1.0.1 not working with Forge

### ISSUE THREAD

**Issue by jakey1995abc** [Trikzon/Sneak-Through-Berries#6]
I've added this mod to my modpack for testing ([https://www.curseforge.com/minecraft/modpacks/quality-of-life-qol](url)) and I get the following error on starting up the pack: 
"File sneak-through-berries-1.16.1-1.0.1.jar is a Fabric mod and cannot be loaded"

**Comment by Trikzon** [comment]
That's because as the change log of the file says, I have not updated it to forge yet.
I will be soon but I'm waiting on motivation and forge mappings (if that's even an issue anymore)
