### ISSUE TITLE
Wrong demo video on CurseForge

### ISSUE THREAD

**Issue by NebelNidas** [Trikzon/Sneak-Through-Berries#9]
The demo video [here](https://www.curseforge.com/minecraft/mc-mods/sneak-through-berries-fabric) is about the Flora Doubling Mod:
![image](https://user-images.githubusercontent.com/48808497/102383767-33363180-3fcc-11eb-9d78-99e6f0c35a17.png)

**Comment by Trikzon** [comment]
Oops, thank you for letting me know. It is now fixed
